### ISSUE TITLE
bug: 일부 페이지의 상품코드가 제대로 추출하지 못하는 오류

### ISSUE THREAD

**Issue by ubeuu** [ubeuu/web-scrap#7]
## Issue
- 다른 레이아웃으로 구성된 게 아닌데도 상품코드를 제대로 추출을 못하는 페이지가 존재한다.
- 기존에 작성했던 태그 클래스명으로 태그를 찾지 못해서 오류가 발생했다.
- 실제 해당 URL을 개발자 도구 페이지에서 필요한 정보가 담긴 태그의 클래스명을 계속 확인해봤지만 전혀 문제가 없었다.
("div.description-text.text-color-grey") 1️⃣
- 하지만 로그를 확인해보니 완전 다른 태그 클래스명을 갖고 있었다.
("div.available-date-component") 2️⃣

## ToDo
- [x] 1️⃣ 클래스명으로 1차 검색 (null이 아닌 경우 그대로 사용)
- [x] 1차 검색 결과가 null인 경우 2️⃣ 클래스명으로 2차 검색 (null이 아닌 경우 그대로 사용)
- [x] 2차 검색 결과가 null인 경우 응답에 상품 코드 항목을 null로 출력

## Other
